version: "3"

services:
  ros:
    build: .
    tty: true
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - LOCAL_USER_ID=1000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./colcon_ws:/root/colcon_ws
      - ./PX4-Autopilot:/root/PX4-Autopilot
